/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author A C E R
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        whitepnl = new javax.swing.JPanel();
        lgnbtn = new javax.swing.JButton();
        Createacc1 = new javax.swing.JLabel();
        sidepnl = new javax.swing.JPanel();
        historybtn = new javax.swing.JButton();
        bookingbtn = new javax.swing.JButton();
        notificationbtn = new javax.swing.JButton();
        technicianbtn = new javax.swing.JButton();
        Availablerequest = new javax.swing.JLabel();
        All = new javax.swing.JButton();
        Plumbing = new javax.swing.JButton();
        Electrical = new javax.swing.JButton();
        HVAC = new javax.swing.JButton();
        scrollpane = new javax.swing.JScrollBar();
        dynamicdata = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 41, 59));

        whitepnl.setBackground(new java.awt.Color(255, 255, 255));
        whitepnl.setForeground(new java.awt.Color(204, 204, 204));

        lgnbtn.setForeground(new java.awt.Color(29, 78, 216));
        lgnbtn.setText("➜🚪  Logout");
        lgnbtn.addActionListener(this::lgnbtnActionPerformed);

        Createacc1.setBackground(new java.awt.Color(255, 255, 255));
        Createacc1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Createacc1.setForeground(new java.awt.Color(29, 78, 216));
        Createacc1.setText("Fixly");

        javax.swing.GroupLayout whitepnlLayout = new javax.swing.GroupLayout(whitepnl);
        whitepnl.setLayout(whitepnlLayout);
        whitepnlLayout.setHorizontalGroup(
            whitepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, whitepnlLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Createacc1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1270, Short.MAX_VALUE)
                .addComponent(lgnbtn)
                .addGap(47, 47, 47))
        );
        whitepnlLayout.setVerticalGroup(
            whitepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(whitepnlLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(whitepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgnbtn)
                    .addComponent(Createacc1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        sidepnl.setBackground(new java.awt.Color(30, 41, 59));
        sidepnl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 182, 193)));

        historybtn.setBackground(new java.awt.Color(30, 41, 59));
        historybtn.setForeground(new java.awt.Color(255, 255, 255));
        historybtn.setText("Verify");
        historybtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));
        historybtn.addActionListener(this::historybtnActionPerformed);

        bookingbtn.setBackground(new java.awt.Color(30, 41, 59));
        bookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        bookingbtn.setText("Monitor");
        bookingbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));
        bookingbtn.addActionListener(this::bookingbtnActionPerformed);

        notificationbtn.setBackground(new java.awt.Color(30, 41, 59));
        notificationbtn.setForeground(new java.awt.Color(255, 255, 255));
        notificationbtn.setText("👨‍   Technician");
        notificationbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));

        technicianbtn.setBackground(new java.awt.Color(30, 41, 59));
        technicianbtn.setForeground(new java.awt.Color(255, 255, 255));
        technicianbtn.setText("Settings");
        technicianbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));
        technicianbtn.addActionListener(this::technicianbtnActionPerformed);

        javax.swing.GroupLayout sidepnlLayout = new javax.swing.GroupLayout(sidepnl);
        sidepnl.setLayout(sidepnlLayout);
        sidepnlLayout.setHorizontalGroup(
            sidepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepnlLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(historybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(notificationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(technicianbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        sidepnlLayout.setVerticalGroup(
            sidepnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notificationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(technicianbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        Availablerequest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Availablerequest.setForeground(new java.awt.Color(255, 255, 255));
        Availablerequest.setText("Available  request");

        All.setBackground(new java.awt.Color(30, 41, 59));
        All.setForeground(new java.awt.Color(255, 255, 255));
        All.setText("All");
        All.addActionListener(this::AllActionPerformed);

        Plumbing.setBackground(new java.awt.Color(30, 41, 59));
        Plumbing.setForeground(new java.awt.Color(255, 255, 255));
        Plumbing.setText("Pending");

        Electrical.setBackground(new java.awt.Color(30, 41, 59));
        Electrical.setForeground(new java.awt.Color(255, 255, 255));
        Electrical.setText("Approved");
        Electrical.addActionListener(this::ElectricalActionPerformed);

        HVAC.setBackground(new java.awt.Color(30, 41, 59));
        HVAC.setForeground(new java.awt.Color(255, 255, 255));
        HVAC.setText("Rejected");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(whitepnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sidepnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Availablerequest, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1336, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(All, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Plumbing, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Electrical, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(HVAC, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(dynamicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 1371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(whitepnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Availablerequest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(All)
                            .addComponent(Plumbing)
                            .addComponent(Electrical)
                            .addComponent(HVAC))
                        .addGap(82, 82, 82)
                        .addComponent(dynamicdata, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrollpane, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addComponent(sidepnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lgnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnbtnActionPerformed

    private void historybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historybtnActionPerformed

    private void bookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbtnActionPerformed

    private void AllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllActionPerformed

    private void ElectricalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElectricalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ElectricalActionPerformed

    private void technicianbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_technicianbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_technicianbtnActionPerformed
private javax.swing.JPanel requestsPanel;

public void initPendingPanel() {
    requestsPanel = new javax.swing.JPanel();
    requestsPanel.setLayout(new javax.swing.BoxLayout(
        requestsPanel, javax.swing.BoxLayout.Y_AXIS));
    requestsPanel.setBackground(new java.awt.Color(30, 41, 59));
    dynamicdata.setViewportView(requestsPanel);
}

public void loadPendingTechnicians(java.util.List<model.UserData> list,
        java.util.function.Consumer<Integer> onApprove,
        java.util.function.Consumer<Integer> onReject,
        java.util.function.Consumer<Integer> onViewCertificate) {
    requestsPanel.removeAll();
    if (list.isEmpty()) {
        javax.swing.JLabel empty = new javax.swing.JLabel("No pending applications.");
        empty.setForeground(java.awt.Color.WHITE);
        empty.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        requestsPanel.add(empty);
    } else {
        for (model.UserData t : list) {
            requestsPanel.add(createTechCard(t, onApprove, onReject, onViewCertificate));
            requestsPanel.add(javax.swing.Box.createVerticalStrut(10));
        }
    }
    requestsPanel.revalidate();
    requestsPanel.repaint();
}

private javax.swing.JPanel createTechCard(model.UserData t,
        java.util.function.Consumer<Integer> onApprove,
        java.util.function.Consumer<Integer> onReject,
        java.util.function.Consumer<Integer> onViewCertificate) {

    javax.swing.JPanel card = new javax.swing.JPanel(new java.awt.BorderLayout(10, 5));
    card.setBackground(new java.awt.Color(51, 65, 85));
    card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 78, 216), 1),
        javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
    ));
    card.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 100));

    javax.swing.JPanel info = new javax.swing.JPanel(new java.awt.GridLayout(0, 1));
    info.setBackground(new java.awt.Color(51, 65, 85));
    info.add(makeLabel("👤  " + t.getUsername()));
    info.add(makeLabel("✉️  " + t.getEmail()));
    info.add(makeLabel("🔧  " + t.getSpecialization()));

    javax.swing.JPanel btns = new javax.swing.JPanel(new java.awt.GridLayout(1, 3, 8, 0));
    btns.setBackground(new java.awt.Color(51, 65, 85));

    javax.swing.JButton certBtn = new javax.swing.JButton("📄 Certificate");
    certBtn.setBackground(new java.awt.Color(59, 130, 246));
    certBtn.setForeground(java.awt.Color.WHITE);
    certBtn.addActionListener(e -> onViewCertificate.accept(t.getId()));

    javax.swing.JButton approveBtn = new javax.swing.JButton("✅ Approve");
    approveBtn.setBackground(new java.awt.Color(34, 197, 94));
    approveBtn.setForeground(java.awt.Color.WHITE);
    approveBtn.addActionListener(e -> onApprove.accept(t.getId()));

    javax.swing.JButton rejectBtn = new javax.swing.JButton("❌ Reject");
    rejectBtn.setBackground(new java.awt.Color(239, 68, 68));
    rejectBtn.setForeground(java.awt.Color.WHITE);
    rejectBtn.addActionListener(e -> onReject.accept(t.getId()));

    btns.add(certBtn);
    btns.add(approveBtn);
    btns.add(rejectBtn);

    card.add(info, java.awt.BorderLayout.CENTER);
    card.add(btns, java.awt.BorderLayout.EAST);
    return card;
}

public void showCertificatePreview(String certPath) {
    new CertificatePreviewDialog(this, certPath).setVisible(true);
}

public void addLogoutListener(java.awt.event.ActionListener l) {
    lgnbtn.addActionListener(l);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton All;
    private javax.swing.JLabel Availablerequest;
    private javax.swing.JLabel Createacc1;
    private javax.swing.JButton Electrical;
    private javax.swing.JButton HVAC;
    private javax.swing.JButton Plumbing;
    private javax.swing.JButton bookingbtn;
    private javax.swing.JScrollPane dynamicdata;
    private javax.swing.JButton historybtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lgnbtn;
    private javax.swing.JButton notificationbtn;
    private javax.swing.JScrollBar scrollpane;
    private javax.swing.JPanel sidepnl;
    private javax.swing.JButton technicianbtn;
    private javax.swing.JPanel whitepnl;
    // End of variables declaration//GEN-END:variables
}
