/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Omne
 */
public class AdminMonitorCard extends javax.swing.JPanel {

    /**
     * Creates new form AdminMonitorCard
     */
    public AdminMonitorCard() {
        initComponents();
    }
public AdminMonitorCard(String typeText, String emailText, String detailsText, String dateText) {
    initComponents();
    type.setText(typeText);
    emailbl.setText(emailText);
    detailslbl.setText(detailsText);
    datelbl.setText(dateText);

    this.setBackground(new java.awt.Color(30, 41, 59));
    this.setOpaque(true);
    this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

    bgpnl.setBackground(new java.awt.Color(30, 41, 59));
    bgpnl.setOpaque(true);
    bgpnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

    uppnl.setBackground(new java.awt.Color(51, 65, 85));
    uppnl.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

    setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
    setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, getPreferredSize().height));
}

@Override
public java.awt.Dimension getMaximumSize() {
    return new java.awt.Dimension(Integer.MAX_VALUE, getPreferredSize().height);
}

public void addApproveListener(java.awt.event.ActionListener listener) {
    apprvbtn.addActionListener(listener);
}

public void addDeclineListener(java.awt.event.ActionListener listener) {
    decbtn.addActionListener(listener);
}

public void addProvideProofListener(java.awt.event.ActionListener listener) {
    certbtn.addActionListener(listener);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpnl = new javax.swing.JPanel();
        uppnl = new javax.swing.JPanel();
        type = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        detailslbl = new javax.swing.JLabel();
        apprvbtn = new javax.swing.JButton();
        decbtn = new javax.swing.JButton();
        certbtn = new javax.swing.JButton();
        emailbl = new javax.swing.JLabel();

        uppnl.setBackground(new java.awt.Color(51, 65, 85));
        uppnl.setPreferredSize(new java.awt.Dimension(1300, 100));

        type.setBackground(new java.awt.Color(51, 65, 85));
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setOpaque(true);

        datelbl.setBackground(new java.awt.Color(51, 65, 85));
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setOpaque(true);

        detailslbl.setBackground(new java.awt.Color(51, 65, 85));
        detailslbl.setForeground(new java.awt.Color(255, 255, 255));
        detailslbl.setOpaque(true);

        apprvbtn.setBackground(new java.awt.Color(51, 65, 85));
        apprvbtn.setForeground(new java.awt.Color(255, 255, 255));
        apprvbtn.setText("Approve");

        decbtn.setBackground(new java.awt.Color(51, 65, 85));
        decbtn.setForeground(new java.awt.Color(255, 255, 255));
        decbtn.setText("Decline");

        certbtn.setBackground(new java.awt.Color(51, 65, 85));
        certbtn.setForeground(new java.awt.Color(255, 255, 255));
        certbtn.setText("Provide Proof");

        emailbl.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout uppnlLayout = new javax.swing.GroupLayout(uppnl);
        uppnl.setLayout(uppnlLayout);
        uppnlLayout.setHorizontalGroup(
            uppnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uppnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emailbl, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(uppnlLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(detailslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addComponent(apprvbtn)
                .addGap(53, 53, 53)
                .addComponent(decbtn)
                .addGap(46, 46, 46)
                .addComponent(certbtn)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        uppnlLayout.setVerticalGroup(
            uppnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uppnlLayout.createSequentialGroup()
                .addGroup(uppnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uppnlLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uppnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(uppnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datelbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(uppnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(uppnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailslbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, uppnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(uppnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apprvbtn)
                            .addComponent(decbtn)
                            .addComponent(certbtn))
                        .addGap(14, 14, 14))))
        );

        javax.swing.GroupLayout bgpnlLayout = new javax.swing.GroupLayout(bgpnl);
        bgpnl.setLayout(bgpnlLayout);
        bgpnlLayout.setHorizontalGroup(
            bgpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(bgpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpnlLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(uppnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgpnlLayout.setVerticalGroup(
            bgpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(bgpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgpnlLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(uppnl, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apprvbtn;
    private javax.swing.JPanel bgpnl;
    private javax.swing.JButton certbtn;
    private javax.swing.JLabel datelbl;
    private javax.swing.JButton decbtn;
    private javax.swing.JLabel detailslbl;
    private javax.swing.JLabel emailbl;
    private javax.swing.JLabel type;
    private javax.swing.JPanel uppnl;
    // End of variables declaration//GEN-END:variables
}
