/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Omne
 */
public class HistoryCard extends javax.swing.JPanel {

    /**
     * Creates new form HistoryCard
     */
    public HistoryCard() {
        initComponents();
    }
    public HistoryCard(String typeText, String detailsText, String dateText) {
    this(typeText, detailsText, dateText, null);
}

public HistoryCard(String typeText, String detailsText, String dateText, String status) {
    initComponents();

    type.setText(typeText);
    detailslbl.setText(detailsText);
    datelbl.setText(dateText);

    applyStatus(status);
}

private void applyStatus(String status) {
    if ("awaiting_payment".equals(status)) {
        confbtn.setVisible(true);
        confbtn.setEnabled(true);
        confbtn.setText("Already Paid");
    } else if ("payment_submitted".equals(status)) {
        confbtn.setVisible(true);
        confbtn.setEnabled(false);
        confbtn.setText("Payment Submitted — Awaiting Verification");
    } else {
        confbtn.setVisible(false);
    }
}

public void addConfirmListener(java.awt.event.ActionListener listener) {
    confbtn.addActionListener(listener);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        detailslbl = new javax.swing.JLabel();
        confbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 65, 85));
        setForeground(new java.awt.Color(255, 255, 255));

        type.setBackground(new java.awt.Color(51, 65, 85));
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setOpaque(true);

        datelbl.setBackground(new java.awt.Color(51, 65, 85));
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setOpaque(true);

        detailslbl.setBackground(new java.awt.Color(51, 65, 85));
        detailslbl.setForeground(new java.awt.Color(255, 255, 255));
        detailslbl.setOpaque(true);

        confbtn.setBackground(new java.awt.Color(51, 65, 85));
        confbtn.setForeground(new java.awt.Color(255, 255, 255));
        confbtn.setText("Already Paid");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 905, Short.MAX_VALUE)
                .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(detailslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confbtn)
                .addGap(226, 226, 226))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(confbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(detailslbl, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confbtn;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel detailslbl;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
