/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Omne
 */
public class NotificationCard extends javax.swing.JPanel {

    /**
     * Creates new form NotificationCard
     */
    public NotificationCard() {
        initComponents();
    }
    public NotificationCard(String typeText, String detailsText, String dateText) {
    initComponents();
    type.setText(typeText);
    detailslbl.setText(detailsText);
    datelbl.setText(dateText);
    
}
    public NotificationCard(String typeText, String detailsText, String dateText, String status) {
    initComponents();
    type.setText(typeText);
    detailslbl.setText(detailsText);
    datelbl.setText(dateText);
    applyStatusColor(status);
}

private void applyStatusColor(String status) {
    java.awt.Color statusColor;
    if (status == null) status = "";
    switch (status.toLowerCase()) {
        case "pending":
            statusColor = new java.awt.Color(234, 179, 8); // yellow
            break;
        case "rejected":
        case "declined":
            statusColor = new java.awt.Color(239, 68, 68); // red
            break;
        case "accepted":
        case "approved":
        case "completed":
            statusColor = new java.awt.Color(34, 197, 94); // green
            break;
        default:
            statusColor = new java.awt.Color(29, 78, 216); // default blue
    }
    // Only change text color — NOT the label background
    type.setForeground(statusColor);
    type.setOpaque(false); // ensure label background doesn't show
    setBorder(javax.swing.BorderFactory.createCompoundBorder(
        javax.swing.BorderFactory.createLineBorder(statusColor, 1),
        javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5)
    ));
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        detailslbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 65, 85));
        setPreferredSize(new java.awt.Dimension(1300, 100));

        type.setBackground(new java.awt.Color(51, 65, 85));
        type.setForeground(new java.awt.Color(255, 255, 255));
        type.setOpaque(true);

        datelbl.setBackground(new java.awt.Color(51, 65, 85));
        datelbl.setForeground(new java.awt.Color(255, 255, 255));
        datelbl.setOpaque(true);

        detailslbl.setBackground(new java.awt.Color(51, 65, 85));
        detailslbl.setForeground(new java.awt.Color(255, 255, 255));
        detailslbl.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(detailslbl, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 581, Short.MAX_VALUE)
                .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailslbl, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel detailslbl;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
