/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */
public class signupfortechnician extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(signupfortechnician.class.getName());

    public signupfortechnician() {
        initComponents();
    }
private String certificationImagePath = "";

public void addSignupListener(java.awt.event.ActionListener l) { 
    sgnbtn.addActionListener(l); 
}

public void addLoginListener(java.awt.event.ActionListener l) {
    // wire back to home if you add a login button
}

public String getFullName()        { return fullnametxt.getText().trim(); }
public String getEmail()           { return emailtxt.getText().trim(); }
public String getPassword()        { return new String(jPasswordField2.getPassword()).trim(); }
public String getConfirmPassword() { return new String(pswfield2.getPassword()).trim(); }
public String getSpecialization()  { return (String) specializationDropdown.getSelectedItem(); }
public String getCertificationPath() { return certificationImagePath; }

public void browseFile() {
    javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
    chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
        "Image Files", "jpg", "jpeg", "png", "pdf"));
    int result = chooser.showOpenDialog(this);
    if (result == javax.swing.JFileChooser.APPROVE_OPTION) {
        certificationImagePath = chooser.getSelectedFile().getAbsolutePath();
        certlabel.setText(chooser.getSelectedFile().getName());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        Createacc = new javax.swing.JLabel();
        getstarted = new javax.swing.JLabel();
        namelabel = new javax.swing.JLabel();
        fullnametxt = new javax.swing.JTextField();
        emaillbl = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        passwordlbl = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        confpswlbl = new javax.swing.JLabel();
        pswcheckbox = new javax.swing.JCheckBox();
        contactlbl = new javax.swing.JLabel();
        pswfield2 = new javax.swing.JPasswordField();
        deptlbl = new javax.swing.JLabel();
        sgnbtn = new javax.swing.JButton();
        specializationDropdown = new javax.swing.JComboBox<>();
        certlabel = new javax.swing.JLabel();
        browsebtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgpanel.setBackground(new java.awt.Color(30, 41, 59));
        bgpanel.setPreferredSize(new java.awt.Dimension(1556, 840));

        Createacc.setBackground(new java.awt.Color(255, 255, 255));
        Createacc.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Createacc.setForeground(new java.awt.Color(29, 78, 216));
        Createacc.setText("Create Account For Technician");

        getstarted.setForeground(new java.awt.Color(204, 204, 204));
        getstarted.setText("Sign up to get started");

        namelabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 255, 255));
        namelabel.setText("Full Name");

        fullnametxt.addActionListener(this::fullnametxtActionPerformed);

        emaillbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emaillbl.setForeground(new java.awt.Color(255, 255, 255));
        emaillbl.setText("Email");

        emailtxt.addActionListener(this::emailtxtActionPerformed);

        passwordlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordlbl.setForeground(new java.awt.Color(255, 255, 255));
        passwordlbl.setText("Password");

        confpswlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confpswlbl.setForeground(new java.awt.Color(255, 255, 255));
        confpswlbl.setText("Confirm Password");

        pswcheckbox.setBackground(new java.awt.Color(30, 41, 59));
        pswcheckbox.setForeground(new java.awt.Color(255, 255, 255));
        pswcheckbox.setText("Show Password");
        pswcheckbox.setOpaque(true);
        pswcheckbox.addActionListener(this::pswcheckboxActionPerformed);

        contactlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactlbl.setForeground(new java.awt.Color(255, 255, 255));
        contactlbl.setText("Contact Number");

        pswfield2.addActionListener(this::pswfield2ActionPerformed);

        deptlbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deptlbl.setForeground(new java.awt.Color(255, 255, 255));
        deptlbl.setText("Department");

        sgnbtn.setBackground(new java.awt.Color(29, 78, 216));
        sgnbtn.setForeground(new java.awt.Color(255, 255, 255));
        sgnbtn.setText("Sign up");

        specializationDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Your Specialization", "Carpenter", "AC Repair", "Painting", "Plumber", "Electrician", "Cleaning", " " }));

        certlabel.setForeground(new java.awt.Color(255, 255, 255));
        certlabel.setText("No File Chosen");

        browsebtn.setText("Browse Certification");
        browsebtn.addActionListener(this::browsebtnActionPerformed);

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout bgpanelLayout = new javax.swing.GroupLayout(bgpanel);
        bgpanel.setLayout(bgpanelLayout);
        bgpanelLayout.setHorizontalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sgnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(579, 579, 579))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pswcheckbox)
                .addGap(338, 338, 338))
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGap(496, 496, 496)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgpanelLayout.createSequentialGroup()
                        .addComponent(specializationDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(browsebtn))
                    .addComponent(getstarted)
                    .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(emailtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                        .addComponent(deptlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordlbl, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emaillbl, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namelabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(contactlbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fullnametxt, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(pswfield2, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addComponent(confpswlbl)
                    .addComponent(Createacc)
                    .addComponent(certlabel)
                    .addComponent(jTextField1))
                .addGap(0, 440, Short.MAX_VALUE))
        );
        bgpanelLayout.setVerticalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(Createacc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(getstarted)
                .addGap(35, 35, 35)
                .addComponent(namelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(emaillbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pswcheckbox)
                .addGap(5, 5, 5)
                .addComponent(confpswlbl)
                .addGap(10, 10, 10)
                .addComponent(pswfield2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(contactlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deptlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specializationDropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browsebtn))
                .addGap(18, 18, 18)
                .addComponent(certlabel)
                .addGap(12, 12, 12)
                .addComponent(sgnbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bgpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnametxtActionPerformed

    private void emailtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtxtActionPerformed

    private void pswcheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswcheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswcheckboxActionPerformed

    private void pswfield2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswfield2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswfield2ActionPerformed

    private void browsebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browsebtnActionPerformed
 browseFile();        // TODO add your handling code here:
    }//GEN-LAST:event_browsebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new signupfortechnician().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Createacc;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JButton browsebtn;
    private javax.swing.JLabel certlabel;
    private javax.swing.JLabel confpswlbl;
    private javax.swing.JLabel contactlbl;
    private javax.swing.JLabel deptlbl;
    private javax.swing.JLabel emaillbl;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JTextField fullnametxt;
    private javax.swing.JLabel getstarted;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel namelabel;
    private javax.swing.JLabel passwordlbl;
    private javax.swing.JCheckBox pswcheckbox;
    private javax.swing.JPasswordField pswfield2;
    private javax.swing.JButton sgnbtn;
    private javax.swing.JComboBox<String> specializationDropdown;
    // End of variables declaration//GEN-END:variables
}
