/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author Omne
 */
public class TechnicianRequestCard extends javax.swing.JPanel {

    /**
     * Creates new form TechnicianRequestCard
     */
    public TechnicianRequestCard() {
        initComponents();
        fixBackground();
    }

    private void fixBackground() {
        java.awt.Color dark = new java.awt.Color(30, 41, 59);
        setBackground(dark);
        setOpaque(true);
        // bg is already #334155, no change needed for the inner card
    }

    public void setCardData(String serviceType, String addressText, String dateText, String statusText, String notesText) {
        type.setText("🔧 " + serviceType);
        type.setForeground(java.awt.Color.WHITE);
        address.setText("📍 " + addressText);
        address.setForeground(java.awt.Color.WHITE);
        date.setText("📅 " + dateText);
        date.setForeground(java.awt.Color.WHITE);
        notes.setText("📝 " + notesText);
        notes.setForeground(java.awt.Color.WHITE);

        // Color-code the status TEXT only (no background change)
        status.setText("⚡ " + statusText);
        switch (statusText == null ? "" : statusText.toLowerCase()) {
            case "accepted":
                status.setForeground(new java.awt.Color(34, 197, 94)); // green
                break;
            case "pending":
                status.setForeground(new java.awt.Color(250, 204, 21)); // yellow
                break;
            case "rejected":
            case "declined":
                status.setForeground(new java.awt.Color(239, 68, 68)); // red
                break;
            default:
                status.setForeground(java.awt.Color.WHITE);
        }
    }

    public void addAcceptListener(java.awt.event.ActionListener l)   { accbtn.addActionListener(l); }
    public void addDeclineListener(java.awt.event.ActionListener l)  { dlcbtn.addActionListener(l); }
    public void addCompleteListener(java.awt.event.ActionListener l) { complted.addActionListener(l); }

    /** Show Accept + Decline, hide Complete (for pending requests) */
    public void showPendingButtons() {
        accbtn.setVisible(true);
        dlcbtn.setVisible(true);
        complted.setVisible(false);
    }

    /** Hide Accept + Decline, show Complete (for already-accepted requests) */
    public void showAcceptedButtons() {
        accbtn.setVisible(false);
        dlcbtn.setVisible(false);
        complted.setVisible(true);
        complted.setBackground(new java.awt.Color(22, 163, 74)); // green
        complted.setForeground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        notes = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        accbtn = new javax.swing.JButton();
        dlcbtn = new javax.swing.JButton();
        complted = new javax.swing.JButton();

        bg.setBackground(new java.awt.Color(51, 65, 85));

        notes.setForeground(new java.awt.Color(255, 255, 255));

        status.setForeground(new java.awt.Color(255, 255, 255));

        type.setForeground(new java.awt.Color(255, 255, 255));

        address.setForeground(new java.awt.Color(255, 255, 255));

        date.setForeground(new java.awt.Color(255, 255, 255));

        accbtn.setBackground(new java.awt.Color(51, 65, 85));
        accbtn.setForeground(new java.awt.Color(255, 255, 255));
        accbtn.setText("Accept");

        dlcbtn.setBackground(new java.awt.Color(51, 65, 85));
        dlcbtn.setForeground(new java.awt.Color(255, 255, 255));
        dlcbtn.setText("Decline");

        complted.setBackground(new java.awt.Color(51, 65, 85));
        complted.setForeground(new java.awt.Color(255, 255, 255));
        complted.setText("Completed");
        complted.setToolTipText("");

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168)
                .addComponent(notes, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accbtn)
                .addGap(18, 18, 18)
                .addComponent(dlcbtn)
                .addGap(18, 18, 18)
                .addComponent(complted)
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                    .addContainerGap(1066, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(7, 7, 7)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(notes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accbtn)
                    .addComponent(dlcbtn)
                    .addComponent(complted))
                .addContainerGap())
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accbtn;
    private javax.swing.JLabel address;
    private javax.swing.JPanel bg;
    private javax.swing.JButton complted;
    private javax.swing.JLabel date;
    private javax.swing.JButton dlcbtn;
    private javax.swing.JLabel notes;
    private javax.swing.JLabel status;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
