package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Omne
 */
public class TechNoti extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TechNoti.class.getName());

    /**
     * Creates new form TechNoti
     */
    public TechNoti() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lgnbtn = new javax.swing.JButton();
        Createacc1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        historybtn = new javax.swing.JButton();
        bookingbtn = new javax.swing.JButton();
        notificationbtn = new javax.swing.JButton();
        technicianbtn = new javax.swing.JButton();
        notification = new javax.swing.JLabel();
        scrollpanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(30, 41, 59));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(204, 204, 204));

        lgnbtn.setForeground(new java.awt.Color(29, 78, 216));
        lgnbtn.setText("➜🚪  Logout");
        lgnbtn.addActionListener(this::lgnbtnActionPerformed);

        Createacc1.setBackground(new java.awt.Color(255, 255, 255));
        Createacc1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Createacc1.setForeground(new java.awt.Color(29, 78, 216));
        Createacc1.setText("Fixly");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Createacc1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1270, Short.MAX_VALUE)
                .addComponent(lgnbtn)
                .addGap(47, 47, 47))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgnbtn)
                    .addComponent(Createacc1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(30, 41, 59));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 182, 193)));

        historybtn.setBackground(new java.awt.Color(30, 41, 59));
        historybtn.setForeground(new java.awt.Color(255, 255, 255));
        historybtn.setText("Request");
        historybtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));
        historybtn.addActionListener(this::historybtnActionPerformed);

        bookingbtn.setBackground(new java.awt.Color(30, 41, 59));
        bookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        bookingbtn.setText("🕓   History");
        bookingbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));
        bookingbtn.addActionListener(this::bookingbtnActionPerformed);

        notificationbtn.setBackground(new java.awt.Color(30, 41, 59));
        notificationbtn.setForeground(new java.awt.Color(255, 255, 255));
        notificationbtn.setText("🔔   Notification");
        notificationbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));

        technicianbtn.setBackground(new java.awt.Color(30, 41, 59));
        technicianbtn.setForeground(new java.awt.Color(255, 255, 255));
        technicianbtn.setText("👨‍   Profile");
        technicianbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(historybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(notificationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(technicianbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notificationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(technicianbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        notification.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        notification.setForeground(new java.awt.Color(255, 255, 255));
        notification.setText("Notification & Updates");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1429, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(645, 645, 645)
                        .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(scrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lgnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnbtnActionPerformed

    private void historybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historybtnActionPerformed

    private void bookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbtnActionPerformed
private javax.swing.JPanel notiPanel;

public void initNotificationPanel() {
    notiPanel = new javax.swing.JPanel();
    notiPanel.setLayout(new javax.swing.BoxLayout(notiPanel, javax.swing.BoxLayout.Y_AXIS));
    notiPanel.setBackground(new java.awt.Color(30, 41, 59));
    scrollpanel.setViewportView(notiPanel);
    scrollpanel.setBorder(null);
    scrollpanel.getViewport().setBackground(new java.awt.Color(30, 41, 59));
}

public void loadNotifications(java.util.List<String[]> notifications) {
    notiPanel.removeAll();
    if (notifications.isEmpty()) {
        javax.swing.JLabel empty = new javax.swing.JLabel("No notifications yet.");
        empty.setForeground(java.awt.Color.WHITE);
        empty.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        notiPanel.add(empty);
    } else {
        for (String[] n : notifications) {
            NotificationCard card = new NotificationCard(n[0], n[1], n[2], n[3]);
            card.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 110));
            card.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            notiPanel.add(card);
            notiPanel.add(javax.swing.Box.createVerticalStrut(10));
        }
    }
    notiPanel.revalidate();
    notiPanel.repaint();
}

public void addBackListener(java.awt.event.ActionListener l) {
    lgnbtn.addActionListener(l);
}

public void addHistoryNavListener(java.awt.event.ActionListener l)      { historybtn.addActionListener(l); }
public void addBookingNavListener(java.awt.event.ActionListener l)      { bookingbtn.addActionListener(l); }
public void addNotificationNavListener(java.awt.event.ActionListener l) { notificationbtn.addActionListener(l); }
public void addProfileNavListener(java.awt.event.ActionListener l)      { technicianbtn.addActionListener(l); }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TechNoti().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Createacc1;
    private javax.swing.JButton bookingbtn;
    private javax.swing.JButton historybtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton lgnbtn;
    private javax.swing.JLabel notification;
    private javax.swing.JButton notificationbtn;
    private javax.swing.JScrollPane scrollpanel;
    private javax.swing.JButton technicianbtn;
    // End of variables declaration//GEN-END:variables
}
