/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author A C E R
 */
public class TechnicianDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TechnicianDashboard.class.getName());

    /**
     * Creates new form verifyrequest
     */
    public TechnicianDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lgnbtn = new javax.swing.JButton();
        Createacc1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        historybtn = new javax.swing.JButton();
        bookingbtn = new javax.swing.JButton();
        notificationbtn = new javax.swing.JButton();
        technicianbtn = new javax.swing.JButton();
        Verifyrequest = new javax.swing.JLabel();
        All = new javax.swing.JButton();
        electrical = new javax.swing.JButton();
        Plumbing = new javax.swing.JButton();
        Carpenter = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        AC = new javax.swing.JButton();
        Painter = new javax.swing.JButton();
        plumber = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 41, 59));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(204, 204, 204));

        lgnbtn.setForeground(new java.awt.Color(29, 78, 216));
        lgnbtn.setText("➜🚪  Logout");
        lgnbtn.addActionListener(this::lgnbtnActionPerformed);

        Createacc1.setBackground(new java.awt.Color(255, 255, 255));
        Createacc1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        Createacc1.setForeground(new java.awt.Color(29, 78, 216));
        Createacc1.setText("Fixly");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Createacc1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lgnbtn)
                .addGap(47, 47, 47))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lgnbtn)
                    .addComponent(Createacc1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(30, 41, 59));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 182, 193)));

        historybtn.setBackground(new java.awt.Color(30, 41, 59));
        historybtn.setForeground(new java.awt.Color(255, 255, 255));
        historybtn.setText("Request");
        historybtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));
        historybtn.addActionListener(this::historybtnActionPerformed);

        bookingbtn.setBackground(new java.awt.Color(30, 41, 59));
        bookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        bookingbtn.setText("🕓   History");
        bookingbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));
        bookingbtn.addActionListener(this::bookingbtnActionPerformed);

        notificationbtn.setBackground(new java.awt.Color(30, 41, 59));
        notificationbtn.setForeground(new java.awt.Color(255, 255, 255));
        notificationbtn.setText("🔔   Notification");
        notificationbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));

        technicianbtn.setBackground(new java.awt.Color(30, 41, 59));
        technicianbtn.setForeground(new java.awt.Color(255, 255, 255));
        technicianbtn.setText("👨‍   Profile");
        technicianbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 65, 85)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(historybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bookingbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(notificationbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(technicianbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historybtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notificationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(technicianbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );

        Verifyrequest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Verifyrequest.setForeground(new java.awt.Color(255, 255, 255));
        Verifyrequest.setText("Verify request");

        All.setBackground(new java.awt.Color(30, 41, 59));
        All.setForeground(new java.awt.Color(255, 255, 255));
        All.setText("All");

        electrical.setBackground(new java.awt.Color(30, 41, 59));
        electrical.setForeground(new java.awt.Color(255, 255, 255));
        electrical.setText("Electrical");

        Plumbing.setBackground(new java.awt.Color(30, 41, 59));
        Plumbing.setForeground(new java.awt.Color(255, 255, 255));
        Plumbing.setText("Plumbing");

        Carpenter.setBackground(new java.awt.Color(30, 41, 59));
        Carpenter.setForeground(new java.awt.Color(255, 255, 255));
        Carpenter.setText("Carpenter");

        AC.setBackground(new java.awt.Color(30, 41, 59));
        AC.setForeground(new java.awt.Color(255, 255, 255));
        AC.setText("AC");
        AC.setToolTipText("");

        Painter.setBackground(new java.awt.Color(30, 41, 59));
        Painter.setForeground(new java.awt.Color(255, 255, 255));
        Painter.setText("Painter");
        Painter.setToolTipText("");

        plumber.setBackground(new java.awt.Color(30, 41, 59));
        plumber.setForeground(new java.awt.Color(255, 255, 255));
        plumber.setText("Plumber");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(All, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(electrical, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Plumbing, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Painter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Carpenter, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(plumber, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Verifyrequest, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Verifyrequest)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(All)
                            .addComponent(electrical)
                            .addComponent(Plumbing)
                            .addComponent(Carpenter)
                            .addComponent(AC)
                            .addComponent(Painter)
                            .addComponent(plumber))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lgnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgnbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lgnbtnActionPerformed

    private void historybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historybtnActionPerformed

    private void bookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingbtnActionPerformed
private int technicianId;
private String username;
private javax.swing.JPanel requestsPanel;
private javax.swing.JPanel historyPanel;

public void setTechnicianId(int technicianId) { this.technicianId = technicianId; }
public void setUsername(String username) { this.username = username; }

// ── Requests Panel ──────────────────────────────────────────────────────────
public void initRequestsPanel() {
    requestsPanel = new javax.swing.JPanel();
    requestsPanel.setLayout(new javax.swing.BoxLayout(requestsPanel, javax.swing.BoxLayout.Y_AXIS));
    requestsPanel.setBackground(new java.awt.Color(30, 41, 59));
    requestsPanel.setOpaque(true);
    jScrollPane1.setBorder(null);
    jScrollPane1.getViewport().setBackground(new java.awt.Color(30, 41, 59));
    jScrollPane1.setViewportView(requestsPanel);
    Verifyrequest.setText("📋 Pending Requests");
}

public void showRequestPanel() {
    jScrollPane1.setViewportView(requestsPanel);
    Verifyrequest.setText("📋 Pending Requests");
    requestsPanel.revalidate();
    requestsPanel.repaint();
}

public void loadAppointments(java.util.List<model.Appointment> appointments, 
                             java.util.function.Consumer<Integer> onAccept, 
                             java.util.function.Consumer<Integer> onReject,
                             java.util.function.Consumer<Integer> onComplete) {
    requestsPanel.removeAll();
    if (appointments.isEmpty()) {
        javax.swing.JLabel empty = new javax.swing.JLabel("No requests found.");
        empty.setForeground(java.awt.Color.WHITE);
        empty.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        requestsPanel.add(empty);
    } else {
        for (model.Appointment a : appointments) {
            TechnicianRequestCard card = new TechnicianRequestCard();
            card.setCardData(a.getServiceType(), a.getAddress(), a.getDate() + "   " + a.getTime(), a.getStatus(), a.getNotes());
            
            if ("accepted".equalsIgnoreCase(a.getStatus())) {
                card.showAcceptedButtons();
                if (onComplete != null) card.addCompleteListener(e -> onComplete.accept(a.getId()));
            } else {
                card.showPendingButtons();
                if (onAccept != null) card.addAcceptListener(e -> onAccept.accept(a.getId()));
                if (onReject != null) card.addDeclineListener(e -> onReject.accept(a.getId()));
            }
            
            card.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 150));
            card.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            requestsPanel.add(card);
            javax.swing.Box.Filler gap = new javax.swing.Box.Filler(
                new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(Short.MAX_VALUE, 6));
            gap.setBackground(new java.awt.Color(30, 41, 59));
            gap.setOpaque(true);
            requestsPanel.add(gap);
        }
    }
    requestsPanel.revalidate();
    requestsPanel.repaint();
}

// ── History Panel ────────────────────────────────────────────────────────────
public void initHistoryPanel() {
    historyPanel = new javax.swing.JPanel();
    historyPanel.setLayout(new javax.swing.BoxLayout(historyPanel, javax.swing.BoxLayout.Y_AXIS));
    historyPanel.setBackground(new java.awt.Color(30, 41, 59));
    historyPanel.setOpaque(true);
}

public void showHistoryPanel() {
    jScrollPane1.setViewportView(historyPanel);
    Verifyrequest.setText("🕓 Job History");
    historyPanel.revalidate();
    historyPanel.repaint();
}

public void loadHistory(java.util.List<model.Appointment> jobs) {
    historyPanel.removeAll();
    if (jobs.isEmpty()) {
        javax.swing.JLabel empty = new javax.swing.JLabel("No history found.");
        empty.setForeground(java.awt.Color.WHITE);
        empty.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        historyPanel.add(empty);
    } else {
        for (model.Appointment a : jobs) {
            TechnicianHistory card = new TechnicianHistory();
            card.setCardData(a.getServiceType(), a.getAddress(), a.getDate() + "  🕐 " + a.getTime(), a.getStatus(), a.getNotes());
            card.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 150));
            card.setAlignmentX(java.awt.Component.LEFT_ALIGNMENT);
            historyPanel.add(card);
            
            javax.swing.Box.Filler gap = new javax.swing.Box.Filler(
                new java.awt.Dimension(0, 6), new java.awt.Dimension(0, 6), new java.awt.Dimension(Short.MAX_VALUE, 6));
            gap.setBackground(new java.awt.Color(30, 41, 59));
            gap.setOpaque(true);
            historyPanel.add(gap);
        }
    }
    historyPanel.revalidate();
    historyPanel.repaint();
}

// ── Listener Methods (View exposes, Controller wires) ──────────────────────
public void addLogoutListener(java.awt.event.ActionListener l) { lgnbtn.addActionListener(l); }
public void addRequestNavListener(java.awt.event.ActionListener l) { historybtn.addActionListener(l); }
public void addHistoryNavListener(java.awt.event.ActionListener l) { bookingbtn.addActionListener(l); }
public void addNotificationNavListener(java.awt.event.ActionListener l) { notificationbtn.addActionListener(l); }
public void addProfileNavListener(java.awt.event.ActionListener l) { technicianbtn.addActionListener(l); }

public void addFilterAllListener(java.awt.event.ActionListener l) { All.addActionListener(l); }
public void addFilterElectricalListener(java.awt.event.ActionListener l) { electrical.addActionListener(l); }
public void addFilterPlumbingListener(java.awt.event.ActionListener l) { Plumbing.addActionListener(l); }
public void addFilterAcListener(java.awt.event.ActionListener l) { AC.addActionListener(l); }
public void addFilterPainterListener(java.awt.event.ActionListener l) { Painter.addActionListener(l); }
public void addFilterCarpenterListener(java.awt.event.ActionListener l) { Carpenter.addActionListener(l); }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TechnicianDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC;
    private javax.swing.JButton All;
    private javax.swing.JButton Carpenter;
    private javax.swing.JLabel Createacc1;
    private javax.swing.JButton Painter;
    private javax.swing.JButton Plumbing;
    private javax.swing.JLabel Verifyrequest;
    private javax.swing.JButton bookingbtn;
    private javax.swing.JButton electrical;
    private javax.swing.JButton historybtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton lgnbtn;
    private javax.swing.JButton notificationbtn;
    private javax.swing.JButton plumber;
    private javax.swing.JButton technicianbtn;
    // End of variables declaration//GEN-END:variables
}
